-- Create editable PRC licensure exam catalog table
create table if not exists public.prc_licensure_exams (
  id bigint generated by default as identity primary key,
  exam_name text not null unique,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

-- Keep updated_at in sync on changes
create or replace function public.set_prc_licensure_exams_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$;

drop trigger if exists trg_set_prc_licensure_exams_updated_at on public.prc_licensure_exams;
create trigger trg_set_prc_licensure_exams_updated_at
before update on public.prc_licensure_exams
for each row
execute function public.set_prc_licensure_exams_updated_at();

-- Seed default exam list (idempotent)
insert into public.prc_licensure_exams (exam_name)
values
  ('Nursing Licensure Examination'),
  ('Criminology Licensure Examination'),
  ('Licensure Examination for Teachers'),
  ('Civil Engineering Licensure Examination'),
  ('Accountancy Licensure Examination'),
  ('Midwifery Licensure Examination')
on conflict (exam_name) do nothing;
