-- Create account_requests table for self-service signup requests.
create table if not exists public.account_requests (
  id bigint generated by default as identity primary key,
  first_name text not null,
  middle_name text,
  last_name text not null,
  email text not null,
  role text not null check (role in ('Student', 'Instructor')),
  prc_exam_type text not null,
  request_message text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  review_notes text,
  reviewed_by text,
  reviewed_at timestamptz,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

-- Keep updated_at current whenever records are modified.
create or replace function public.set_account_requests_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$;

drop trigger if exists trg_set_account_requests_updated_at on public.account_requests;
create trigger trg_set_account_requests_updated_at
before update on public.account_requests
for each row
execute function public.set_account_requests_updated_at();

-- Prevent duplicate pending requests per email.
create unique index if not exists idx_account_requests_pending_email
on public.account_requests (lower(email))
where status = 'pending';

create index if not exists idx_account_requests_status_created_at
on public.account_requests (status, created_at desc);
